### ISSUE TITLE
Report back on OpenCraft's MFE theming discovery

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-coordination#22]
Start March 9th and (possibly) ending March 22nd, OpenCraft will embark on a discovery of how MFE's can be themed.  Report results back to the group.

For reference, [OEROADMAP-13](https://openedx.atlassian.net/browse/OEROADMAP-13) was the original proposal by @bradenmacdonald.

**Comment by arbrandes** [comment]
@xitij2000, mind if I add you as assignee, here?  Mostly to make comms easier.

**Comment by xitij2000** [comment]
@arbrandes Definitely.

**Comment by arbrandes** [comment]
@xitij2000, do you think you could make the discovery public and and link to it here once it's done?

**Comment by xitij2000** [comment]
@arbrandes Certainly!

**Comment by antoviaque** [comment]
Here is the link to the forum thread announcing the results: https://discuss.openedx.org/t/open-edx-branding-and-theming-improvements/4747

And the discovery results themselves, which are open to comments: https://gitlab.com/opencraft/dev/branding-and-theming/-/merge_requests/1

CC @xitij2000

**Comment by antoviaque** [comment]
@xitij2000 Was there an update posted somewhere on this at the end? If so, we could link to it from here, and close this ticket.

**Comment by xitij2000** [comment]
While there was an [initial discovery](https://gitlab.com/opencraft/dev/branding-and-theming/-/merge_requests/3) and we updated it based on the changes in the ecosystem, such as the use of tutor and movement of theming towards design tokens. The task for the theming MFE was [eventually dropped](https://gitlab.com/opencraft/dev/branding-and-theming/-/issues/2#note_1485675687). 

While it is a worthwhile endeavour, the original plan was to use it as a way for our Ocim clients to set up their own instance and theme using a simple UI, and we no longer offer that service, so we no longer have an internal need for it. 

At this point, we're focussing on having CI pipelines that can help automate quick deployment of themes so that quick variable changes can be automatically deployed and pushed to production without rebuilding all the MFEs, using design tokens.

**Comment by antoviaque** [comment]
@xitij2000 Thanks for the update! So the way to theme MFEs going forward is through variables - is this already applicable to all MFEs?

**Comment by xitij2000** [comment]
> @xitij2000 Thanks for the update! So the way to theme MFEs going forward is through variables - is this already applicable to all MFEs?

This is still WIP in an alpha branch of Paragon, however, it is the [new mechanism](https://github.com/openedx/paragon/pull/1929) for styling MFEs. Currently, the mechanism we use is to inject variables into  `simple-theme`  using Grove (earlier Ocim) that is built and installed into edx-platform and MFEs. The new mechanism makes it possible to override variables in a better way using design tokens, and there is also [WIP mechanism to do this dynamically](https://github.com/openedx/frontend-platform/pull/440), making it unnecessary to rebuild the MFEs for each theme change. 

I have a WIP version of [simple-theme that uses design tokens](https://github.com/open-craft/edx-simple-theme/pull/34) that I will keep updated as design tokens evolve, and we can merge it when design tokens are fully released.

**Comment by antoviaque** [comment]
Thanks @xitij2000 - sounds good. :+1:
